- name: Consul master is running
  docker:
    name: "{{ consul_name }}"
    hostname: "{{ consul_name }}"
    image: progrium/consul
    net: "{{ network_name }}"
    ports:
     - "8400:8400"
     - "8500:8500"
     - "8600:53/udp"
    command: "-server -bootstrap"
    restart_policy: always
  tags: [consul]
