
- name: install center env
  hosts: center
  become: yes
  
  pre_tasks:
#    - name: install python 
#      raw: apt-get update && apt-get -y install python-simplejson  pip

#    - name: install python-consul 
#      pip: name=python-consul

    - name: Cretae docker create
      shell: docker network create "{{ deploy_env }}-network"

  roles:
    - role: consul
      network_name: "{{ deploy_env }}-network" 
    - role: registrator
      network_name: "{{ deploy_env }}-network"
    - role: nginx-proxy
      service_name: "{{ deploy_env }}.app"
      network_name: "{{ deploy_env }}-network"

  tasks:
    - name: deploy directory is present
      file:
        path: deploy
        state: directory
        mode: 0777

    - name: Copy files to deploy dir
      synchronize : src="files/" dest="deploy"

    - name: exec docker-compare to up service
      shell: docker-compose -f /home/agileuser/deploy/services.yml -f /home/agileuser/deploy/{{ deploy_env }}.yml  --project-name={{ project_release_no }} up -d

    - name: exec docker-compare to scale service
      shell: docker-compose -f /home/agileuser/deploy/services.yml -f /home/agileuser/deploy/{{ deploy_env }}.yml  --project-name={{ project_release_no }} scale {{ scale_service }}
      when {{ scale_service }} != "" 

    - name: add a node to an  group via consul inventory
      delegate_to: localhost
      consul_kv:
        host: 139.196.48.143
        port: 8500
        key: service/node/version/started
        value: "{{ project_release_no }}"