- name: Registrator is running
  docker:
    name: registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    hostname: registrator
    image: gliderlabs/registrator:master
    net: "{{ network_name }}"
    command: "-internal consul://consul:8500"
    links:
      - "{{ consul_name }}:consul"
    restart_policy: always
  tags: [registrator]
