- name: Registrator is running
  docker:
    name: registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    hostname: registrator
    image: gliderlabs/registrator
    net: "{{ network_name }}"
    command: consul://consul:8500
    links:
      - "{{ consul_name }}:consul"
    restart_policy: always
  tags: [registrator]
