- name: Registrator is running
  docker:
    name: registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    hostname: registrator
    image: gliderlabs/registrator
    command: consul://{{ consul_master_ip }}:8500
    restart_policy: always
  tags: [registrator]
