
- name: Nginx-proxy is running
  docker:
    name: nginx-proxy
    hostname: nginx-proxy
    image: agilebot/nginx-proxy
    net: "{{ network_name }}"
    env:
       CONSUL: "consul:8500"
       SERVICE: "{{ service_name }}"
    links:
       - "{{ consul_name }}:consul"
    ports:
      - "8888:80"
    state: restarted
    restart_policy: always
  tags: [nginx-proxy]