version: '2'
services:
  web:
    environment: 
       SERVICE_NAME: app
       SERVICE_TAGS: staging
    external_links:
      - staging-db:mysql
    logging:
      driver: gelf
      options:
        gelf-address: udp://139.196.48.143:12201
        tag: "staging"
        labels: "web"

  db:
    container_name: staging-db
    logging:
      driver: gelf
      options:
        gelf-address: udp://139.196.48.143:12201
        tag: "staging"
        labels: "db"

networks:
  default:
    external:
      name: staging-network


        